(autoload 'bbdb					"bbdb-com" "" t)
(autoload 'bbdb-initialize                      "bbdb" "" nil)
(autoload 'bbdb-mail-aliases                    "bbdb-com" "" t)
(autoload 'bbdb-insinuate-gnus                  "bbdb-gnus" "" nil)
(autoload 'bbdb-insinuate-mail                  "bbdb-message" "" nil)
(autoload 'bbdb-insinuate-message               "bbdb-message" "" nil)
(autoload 'bbdb-insinuate-rmail                 "bbdb-rmail" "" nil)
(autoload 'bbdb-insinuate-vm                    "bbdb-vm" "" nil)
(provide 'bbdb-epkg-install)
